services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - registres-database-data:/var/lib/postgresql   # stock la base de données et assure sa persistance
      - ./registres-database/init.sql:/docker-entrypoint-initdb.d/init.sql   # initialise au premier démarage le script init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  registres-back:
    build: ./registres-back
    ports:
      - "3000:3000"   # SUPPRIMER EN PROD(à gauche ce qui est appelé par le navigateur, à droite ce qu'y est appelé par les conteneurs/environnement)
    volumes:
      - ./registres-back:/app   # fait le reload du dossier sans avoir besoin de faire un nouveau build (hot-reload)
      - registres-back-node_mobuldes:/app/node_modules    # protège les node_modules pour éviter qu'ils se fassent écraser
    env_file:
      - ./registres-back/.env # injection des variables
    command: npm run dev      # commande pour lancer le backend
    depends_on:
      db:
        condition: service_healthy
  
  registres-front:
    build: ./registres-front
    ports:
      - "5173:5173"
    volumes:
      - ./registres-front:/app
      - registres-front-node_modules:/app/node_modules
    command: npm run dev
    environment :
      - VITE_API_URL=http://localhost:3000/api    # url du backend pour l'utiliser au frontend

volumes:
  registres-database-data:
  registres-back:
  registres-front: